# Generated by Django 6.0.5 on 2026-06-16 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In_progress'), ('Finished', 'Finished')], default='To do', max_length=20),
        ),
    ]
